language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.0
    - tools
    - platform-tools
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - chmod +x gradlew
  
licenses:
  - android-sdk-license-.+
  - '.+'

script:
   ./gradlew build
